apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test-workflow

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - kafka.yaml
  - network-policy.yaml
  - ingress.yaml
  - ../services/api-gateway.yaml
  - ../services/order-service.yaml
  - ../services/inventory-service.yaml
  - ../services/notification-service.yaml
  - ../services/frontend.yaml

commonLabels:
  app.kubernetes.io/part-of: test-workflow
  app.kubernetes.io/managed-by: kustomize
